INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD) VALUES (123123, 'john_doe', 'john@example.com', 'password123');
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD) VALUES (234234, 'jane_doe', 'jane@example.com', 'password123');
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD) VALUES (345345, 'my_username', 'my@example.com', 'password123');
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD) VALUES (456456, 'test_username', 'test@example.com', 'password123');
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD) VALUES (567567, 'new_user', 'new@example.com', 'password123');
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD) VALUES (678678, 'one_more_user', 'one@example.com', 'password123');


INSERT INTO WISHLISTS (WISHLIST_ID, USER_ID, NAME, DESCRIPTION) VALUES ( 123, 123123, 'Christmas list', 'List of Christmas presents!' );
INSERT INTO WISHLISTS (WISHLIST_ID, USER_ID, NAME, DESCRIPTION) VALUES ( 234, 234234, 'Christmas list', 'List of Christmas presents!' );
INSERT INTO WISHLISTS (WISHLIST_ID, USER_ID, NAME, DESCRIPTION) VALUES ( 345, 345345, 'Christmas list', 'List of Christmas presents!' );
INSERT INTO WISHLISTS (WISHLIST_ID, USER_ID, NAME, DESCRIPTION) VALUES ( 456, 123123, 'Birthday list', 'List of birthday presents!' );
INSERT INTO WISHLISTS (WISHLIST_ID, USER_ID, NAME, DESCRIPTION) VALUES ( 567, 456456, 'Christmas list', 'List of Christmas presents!' );


INSERT INTO WISHITEMS (WISH_ITEM_ID, NAME, DESCRIPTION, PRICE, WISHLIST_ID) VALUES ( 12, 'Laptop', 'New laptop from Lenovo', 8000, 123 );
INSERT INTO WISHITEMS (WISH_ITEM_ID, NAME, DESCRIPTION, PRICE, WISHLIST_ID) VALUES ( 23, 'Blender', 'New blender from Skousen', 1000, 123 );
INSERT INTO WISHITEMS (WISH_ITEM_ID, NAME, DESCRIPTION, PRICE, WISHLIST_ID) VALUES ( 34, 'Phone', 'New phone from Samsung', 4500, 123 );
INSERT INTO WISHITEMS (WISH_ITEM_ID, NAME, DESCRIPTION, PRICE, WISHLIST_ID) VALUES ( 45, 'Perfume', 'Perfume from Matas', 300, 123 );
INSERT INTO WISHITEMS (WISH_ITEM_ID, NAME, DESCRIPTION, PRICE, WISHLIST_ID) VALUES ( 67, 'Pants', 'New pants from H&M', 200, 123 );